### ISSUE TITLE
[App] Update PayPal payments explanation text

### ISSUE THREAD

**Issue by milanbargiel** [milanbargiel/kulturgenerator#101]
In this text, we should mention, that PayPal takes a fee for money transfers.
For Germany this is 2,49 % + fixed price as described here: https://www.paypal.com/de/webapps/mpp/merchant-fees

>  Durch Anklicken von bezahlen mit Paypal, bestätigen Sie die Weitergabe ihrer angegebenen Daten an die Kulturschaffenden. Das Geld fließt direkt und zu 100% an den/die teilnehmende Künstler*in. Für Fragen zu Abrechnung treten Sie bitte nach dem Kauf direkt mit den Verkäufer*innen in Kontakt. Danke! 

<img width="927" alt="paypal-explanation-text" src="https://user-images.githubusercontent.com/21197498/95553308-945ee900-0a0e-11eb-8ca8-ba0ff3206bac.png">

**Comment by moritzpflueger** [comment]
closed because this is part of the general text review by the content team. @ludwiglederer @katherina-gorod
