### ISSUE TITLE
wrong detail-site at some objects which we recently put online (Pari Moradi, Thomas Baumgärtel, Maurits Boettger)

### ISSUE THREAD

**Issue by katherina-gorod** [milanbargiel/kulturgenerator#160]

**Comment by milanbargiel** [comment]
Actually this behaviout is not a "bug" and I was able to fix it by generating URL-slugs in the Strapi-Backend for all newly created artworks.

When you create an artwork manually in Strapi, without using the web form, you need to generate a slug manually too. If not the artwork detail page url is not unique and you see a wrong detail page.

I created a feature request #172 and close this issue.
