### ISSUE TITLE
[CMS] Improve slug creation process

### ISSUE THREAD

**Issue by milanbargiel** [milanbargiel/kulturgenerator#172]
### requirements
- When an user creates an artwork in the Strapi-Backend xyz.kulturgenerator.org/admin an url-slug shall be generated automatically

### status quo
- After creating an artwork editors have to manually press the generate slug button in the backend
- This was forgotten in the past and an error occured

**Comment by moritzpflueger** [comment]
I Believe this already the case. Reopen if problem occurres again.
