### ISSUE TITLE
[App] fix layout bug for image slider

### ISSUE THREAD

**Issue by moritzpflueger** [milanbargiel/kulturgenerator#177]
### description
Beim Überarbeiten des Layouts wurde eventuell vergessen Bildergallerien zu berücksichtigen.

Die Punkte unter dem Bild sind etwas nach am Autor.

![image](https://user-images.githubusercontent.com/65345718/97973932-24524180-1dc7-11eb-8852-f240c68b2b8d.png)

**Comment by milanbargiel** [comment]
Apparently this bug disappeared with one of the last releases. Please open, when the bug reappears.
