### ISSUE TITLE
[App] fix rel not added in markdown link hack

### ISSUE THREAD

**Issue by moritzpflueger** [milanbargiel/kulturgenerator#219]
### description

added this hack to `ArtworkDetail` to open every link from the artwork detail description. The links added to the description via strapi cannot be configured, that's the reason for the hack.

```js
    // HACK - do open links in a new tab that are in the artwork description
    var links = document.links;
    links.forEach(link => {
      if (link.className.length <= 0 && link.hostname !== window.location.hostname && !link.innerHTML.includes('<u>')) {
        link.target = '_blank'
        link.rel = 'noopener'
      }
    })
```

**Comment by milanbargiel** [comment]
Can this be closed or is it still relevant @moritzpflueger?

**Comment by moritzpflueger** [comment]
This can be closed. Rel should be added with the latest fix.
